channels:
  - rapidsai-nightly
  - nvidia
  - conda-forge
dependencies:
  - cudatoolkit=10.0
  - dask-cuda
  - cudf=0.10
  - dask-cudf
  - cuml
  - cugraph
  - rapidsai/label/xgboost::dask-xgboost=0.2.*
  - gcsfs
  - dill
  - ipykernel
  - pip
  - pip:
    # https://xgboost-ci.net/blue/organizations/jenkins/xgboost/activity
    - https://xgboost-ci.net/job/xgboost/job/master/lastSuccessfulBuild/artifact/python-package/dist/xgboost-1.0.0_SNAPSHOT-py2.py3-none-any.whl
