channels:
  - rapidsai/label/xgboost
  - rapidsai
  - nvidia
  - conda-forge
dependencies:
  - cudatoolkit=10.0
  - dask-cuda
  - cudf=0.9
  - pyarrow=0.14.1
  - arrow-cpp=0.14.1
  - dask-cudf
  - cuml
  - cugraph
  - rapidsai/label/xgboost::xgboost=0.90.*
  - rapidsai/label/xgboost::dask-xgboost=0.2.*
  - gcsfs
  - dill
  - ipykernel
