channels:
  - rapidsai/label/xgboost
  - rapidsai
  - nvidia
  - conda-forge
dependencies:
  - cudatoolkit=10.0
  - dask-cuda=0.9.*
  - cudf=0.9.*
  - pyarrow=0.14.1
  - arrow-cpp=0.14.1
  - dask-cudf=0.9.*
  - cuml=0.9.*
  - dask-cuml=0.9.*
  - cugraph=0.9.*
  - rapidsai/label/xgboost::xgboost=0.90.*
  - rapidsai/label/xgboost::dask-xgboost=0.2.*
  - gcsfs
  - dill
  - ipykernel
